# Numpy Practice Notebook

In [1]:
import numpy as np # Importing numpy library as np 

# Creating Numpy Arrays

## *1-Dimensional array*
1 D array is also known as a vector. 1D array have only one axis

### Simple Array

In [2]:
a1a = np.array([1,2,3,4,5])
a1a

array([1, 2, 3, 4, 5])

### Arrange function

In [3]:
a1b = np.arange(1,10,2) #arange creates an array starts from 1 to 10-1 with steps 2
a1b

array([1, 3, 5, 7, 9])

### Array with zeros

In [4]:
a1c = np.zeros(5) # np.zeros will create an array of (no. of times provided in argument) zeros
a1c

array([0., 0., 0., 0., 0.])

### Array with ones

In [5]:
a1d = np.ones(5) #np.ones create an array of (no. of times provided in argument) ones
a1d

array([1., 1., 1., 1., 1.])

### Empty Array

In [6]:
a1e = np.empty(5) #np.empty creates an empty array of size provided in arguments
a1e

array([1., 1., 1., 1., 1.])

### Linearly spaced array

In [7]:
a1f = np.linspace(2,20,num=10) #linspace creates an equal spaced array with size provided to num variable  
a1f

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### Full array (Array with same number)

In [8]:
a1g = np.full((5,),3) #Creating a vector with same number
a1g

array([3, 3, 3, 3, 3])

### Random numbers array

In [9]:
a1h = np.random.random(3,) #Creating a vector of random numbers between 0 and 1
a1h

array([0.54856612, 0.63046469, 0.67330469])

In [10]:
a1i = np.random.randint(low=0,high=4,size=(5,)) #Creating a vector of random numbers between low and high values
a1i

array([3, 2, 1, 1, 1])

## *2-Dimensional Arrays*
2D array is also known as a matrix. A matrix have 2 axis. axis 0 = columns and axis 1 = rows

### Simple Array

In [11]:
a2a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
a2a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a2b = np.arange(10).reshape(2,5) #Making a Matric of size 10. Note that product of no. of rows and cols should be equal to the size provided in the arguments of arange function
a2b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
a2c = np.zeros((3,3)) #Creating a matrix of 3 rows and 3 columns
a2c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a2d = np.ones((4,5))
a2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
a2e = np.linspace(1,100,num=10).reshape(5,2) # Creating a matrix of linearly spaced numbers of size 5 rows and 2 columns
a2e

array([[  1.,  12.],
       [ 23.,  34.],
       [ 45.,  56.],
       [ 67.,  78.],
       [ 89., 100.]])

In [16]:
a2f = np.full((5,5),3) #Creating a matrix with same number
a2f

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

### Identity Matirx

In [17]:
a2g = np.eye(4,4)
a2g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random numbers matrix

In [18]:
a2h = np.random.random((3,4)) #Creating a matrix of random numbers between 0 and 1
a2h

array([[2.31602544e-01, 1.23259148e-01, 9.64176656e-01, 3.92412739e-01],
       [8.74582761e-02, 5.66857668e-01, 9.20587109e-04, 5.43346034e-01],
       [2.90315151e-01, 6.97928789e-01, 5.23414184e-01, 9.64195302e-01]])

In [19]:
a2i = np.random.randint(low=1,high=6,size=(5,5)) #Creating a matrix of random numbers between low and high values
a2i

array([[1, 2, 2, 2, 1],
       [4, 3, 3, 5, 2],
       [5, 2, 4, 3, 4],
       [2, 4, 3, 4, 3],
       [1, 3, 1, 3, 5]])

## *3-Dimensional Arrays*

### Simple Array

In [20]:
a3a = np.array([
    [[1,2,3],
     [3,2,1],
     [4,5,6]],
    
    [[7,8,9],
     [9,8,7],
     [6,5,4]],
    
    [[9,5,1],
     [1,5,2],
     [8,3,2]]
    ]) # A simple matrix of size (3,3,3) 3 2D arrays having 3 rows and 3 columns
a3a

array([[[1, 2, 3],
        [3, 2, 1],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7],
        [6, 5, 4]],

       [[9, 5, 1],
        [1, 5, 2],
        [8, 3, 2]]])

In [21]:
a3b = np.arange(50).reshape(5,2,5) #Creating a 3D array which includes 5 2D arrays of size 2 rows and 5 columns 
a3b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [22]:
a3c = np.zeros((3,2,3))
a3c

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
a3d = np.ones((4,1,7))
a3d

array([[[1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.]]])

In [24]:
a3e = np.linspace(1, 100, num = 50).reshape(2,5,5)
a3e

array([[[  1.        ,   3.02040816,   5.04081633,   7.06122449,
           9.08163265],
        [ 11.10204082,  13.12244898,  15.14285714,  17.16326531,
          19.18367347],
        [ 21.20408163,  23.2244898 ,  25.24489796,  27.26530612,
          29.28571429],
        [ 31.30612245,  33.32653061,  35.34693878,  37.36734694,
          39.3877551 ],
        [ 41.40816327,  43.42857143,  45.44897959,  47.46938776,
          49.48979592]],

       [[ 51.51020408,  53.53061224,  55.55102041,  57.57142857,
          59.59183673],
        [ 61.6122449 ,  63.63265306,  65.65306122,  67.67346939,
          69.69387755],
        [ 71.71428571,  73.73469388,  75.75510204,  77.7755102 ,
          79.79591837],
        [ 81.81632653,  83.83673469,  85.85714286,  87.87755102,
          89.89795918],
        [ 91.91836735,  93.93877551,  95.95918367,  97.97959184,
         100.        ]]])

In [25]:
a3f = np.random.randint(low = 0, high = 100, size = (2,6,6))
a3f

array([[[32, 19, 64, 40, 23,  6],
        [31, 82, 58, 79, 57, 91],
        [42, 20, 50, 27,  8, 49],
        [ 0, 43, 41, 89, 12, 82],
        [70, 91, 35, 89, 50, 43],
        [75, 45, 51, 59, 75, 90]],

       [[46, 71, 69, 69, 21, 39],
        [60, 37, 12, 67, 58, 50],
        [52, 23, 77, 86, 48, 88],
        [46, 97,  7, 51, 43,  5],
        [52, 72, 60, 17, 86, 82],
        [25, 58, 92, 30, 61, 16]]])

In [26]:
a3g = np.random.random((3,4,3))
a3g

array([[[0.26341879, 0.50055969, 0.81951534],
        [0.02346514, 0.67636781, 0.39886443],
        [0.37597612, 0.57064326, 0.82749506],
        [0.3126915 , 0.49707049, 0.21682798]],

       [[0.97971177, 0.18692455, 0.43781019],
        [0.68223173, 0.58175934, 0.30652476],
        [0.50924333, 0.11087383, 0.95899054],
        [0.53934685, 0.96589934, 0.37428034]],

       [[0.18719464, 0.21329647, 0.05362497],
        [0.77539499, 0.89481268, 0.13077001],
        [0.80274577, 0.30550153, 0.84763637],
        [0.05478349, 0.05768798, 0.00130087]]])

In [27]:
a3h = np.full((2,3,4),5)
a3h

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

## *Size, Shape, Dimension, Type and DataType* 

#### Size
- Size tells us the total number of elements present in the array 

In [28]:
a1a.size # 1D array

5

In [29]:
a2e.size # 2D array

10

In [30]:
a3d.size # 3D array

28

#### Shape
- Shape gives the dimension of the array

In [31]:
a1a.shape #1D array

(5,)

In [32]:
a2f.shape # 2D array

(5, 5)

In [33]:
a3e.shape # 3D array

(2, 5, 5)

#### Type
- Type tells us about the type of the array. ndarray means n dimensional array

In [34]:
type(a1a) # 1D array

numpy.ndarray

In [35]:
type(a2h) # 2D array

numpy.ndarray

In [36]:
type(a3d) # 3D array

numpy.ndarray

#### Data Type
- dtype tells about the data type of the array

In [37]:
a1a.dtype # 1D array

dtype('int32')

In [38]:
a2f.dtype # 2D array

dtype('int32')

In [39]:
a3g.dtype # 3D array

dtype('float64')

#### Dimension
- ndim function is used to know the dimension of a numpy array

In [40]:
a1a.ndim 

1

In [81]:
a2a.ndim

2

In [82]:
a3a.ndim

3

## How to change DataType ?
There are many datatypes like int, float, double, bool.
- astype is used to change the datatype of ndarray

In [41]:
a1a.astype(np.float16) #float16 means 16 bits floating point numbers (1D array)

array([1., 2., 3., 4., 5.], dtype=float16)

In [42]:
a1a.astype(np.uint32) #uint is unsigned integer and 32 is the 32 bits

array([1, 2, 3, 4, 5], dtype=uint32)

In [43]:
a2g.astype(np.uint8) # 2D array

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

In [44]:
a3g.astype(np.float64)

array([[[0.26341879, 0.50055969, 0.81951534],
        [0.02346514, 0.67636781, 0.39886443],
        [0.37597612, 0.57064326, 0.82749506],
        [0.3126915 , 0.49707049, 0.21682798]],

       [[0.97971177, 0.18692455, 0.43781019],
        [0.68223173, 0.58175934, 0.30652476],
        [0.50924333, 0.11087383, 0.95899054],
        [0.53934685, 0.96589934, 0.37428034]],

       [[0.18719464, 0.21329647, 0.05362497],
        [0.77539499, 0.89481268, 0.13077001],
        [0.80274577, 0.30550153, 0.84763637],
        [0.05478349, 0.05768798, 0.00130087]]])

In [45]:
a3g.astype(np.int_) #int_ means long int

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

## *Indexing and Slicing*
- Indexing is used to get a subpart of array
*Note that : Staring index of every array is 0 if we move in forward direction
- Starting Index is -1 in case of backward direction

### Indexing of 1D arrays

In [46]:
a1a

array([1, 2, 3, 4, 5])

In [47]:
# print the first element from array
a1a[0]

1

In [48]:
# print the 3rd element from array
a1a[2]

3

In [49]:
# print the last element from array
a1a[-1] #-1 

5

In [50]:
# print the second last element from array
a1a[-2]

4

In [51]:
# print the 1st three element from array
a1a[0:3] # Note that the 3 index in not included. the elements at index 0,1, and 2 will be print.

array([1, 2, 3])

In [52]:
# print the last 4 element from array
a1a[-4:]

array([2, 3, 4, 5])

In [53]:
# reverse the sequence of elements of array
temp = a1a[::-1] #This prints the elements of index -1 -2 -3 -4 -5. starting index is 0 so 0-1=-1 and it prints 5. -1-1=-2 and it prints 4 and so on...
temp

array([5, 4, 3, 2, 1])

In [83]:
#Another function named np.flip is used to reverse a numpy array
tem = np.flip(a1a)
tem

array([5, 4, 3, 2, 1])

### Indexing of 2D arrays

In [54]:
a2a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
#Print the first index elements 
a2a[0]

array([1, 2, 3, 4])

In [56]:
# Print the 2nd element of index 0
a2a[0,1]

2

In [57]:
# Another way to print the 2nd element of index 0
a2a[0][1]

2

In [58]:
#Print 1st two arrays from a matrix
a2a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Print only 1st elements of the every row
a2a[:,0]

array([1, 5, 9])

In [60]:
#print 6 number from the matrix
a2a[1,1]

6

In [61]:
#Print 3rd element of every row
a2a[:,2]

array([ 3,  7, 11])

In [85]:
# Reverse the order of the arrray
rev_arr = np.flip(a2a)
rev_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### Indexing of 3D arrays

In [62]:
a3a

array([[[1, 2, 3],
        [3, 2, 1],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7],
        [6, 5, 4]],

       [[9, 5, 1],
        [1, 5, 2],
        [8, 3, 2]]])

In [63]:
#Print 1st two 2D arrays
a3a[0:2]

array([[[1, 2, 3],
        [3, 2, 1],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7],
        [6, 5, 4]]])

In [64]:
#Print 2nd row only of all the arrays
a3a[:,1,:]

array([[3, 2, 1],
       [9, 8, 7],
       [1, 5, 2]])

In [65]:
#Print 2nd col only of all the arrays
a3a[:,:,1]

array([[2, 2, 5],
       [8, 8, 5],
       [5, 5, 3]])

In [66]:
#print number '6' from array
a3a[0,2,2]

6

In [87]:
#Reverse the array
rev_arr2 = np.flip(a3a)
rev_arr2

array([[[2, 3, 8],
        [2, 5, 1],
        [1, 5, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [1, 2, 3],
        [3, 2, 1]]])

## *How to change the Dimension of the array?*
- We can do it manually as well as by using expand_dims function 

### Change 1D array to 2D array

In [67]:
#Row wise Expansion (axis = 0)
temp2 = a1a[np.newaxis,:] 
temp2

array([[1, 2, 3, 4, 5]])

In [68]:
temp2.shape

(1, 5)

In [117]:
# Expand_dims function
exp1 = np.expand_dims(a1a,axis=0)
exp1

array([[1, 2, 3, 4, 5]])

In [118]:
exp1.shape

(1, 5)

In [69]:
#Column wise Expansion (axis = 1)
temp3 = a1a[:,np.newaxis]
temp3

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [70]:
temp3.shape

(5, 1)

In [119]:
# Expand_dims function
exp2 = np.expand_dims(a1a,axis=1)
exp2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [120]:
exp2.shape

(5, 1)

### Change 2D array to 3D array

In [71]:
#Row wise Expansion (axis = 0)
temp4 = a2a[np.newaxis,:] 
temp4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [72]:
temp4.shape

(1, 3, 4)

In [121]:
# Expand_dims function
exp3 = np.expand_dims(a2a,axis=0)
exp3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [122]:
exp3.shape

(1, 3, 4)

In [73]:
#Column wise Expansion (axis = 1)
temp5 = a2a[:,np.newaxis]
temp5

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [74]:
temp5.shape

(3, 1, 4)

In [123]:
# Expand_dims function
exp4 = np.expand_dims(a2a,axis=1)
exp4

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [125]:
exp4.shape

(3, 1, 4)

### Change 3D array to 4D array

In [75]:
temp6 = a3a[np.newaxis,:,:]
temp6

array([[[[1, 2, 3],
         [3, 2, 1],
         [4, 5, 6]],

        [[7, 8, 9],
         [9, 8, 7],
         [6, 5, 4]],

        [[9, 5, 1],
         [1, 5, 2],
         [8, 3, 2]]]])

In [76]:
temp7 = a3a[:,np.newaxis,:]
temp7

array([[[[1, 2, 3],
         [3, 2, 1],
         [4, 5, 6]]],


       [[[7, 8, 9],
         [9, 8, 7],
         [6, 5, 4]]],


       [[[9, 5, 1],
         [1, 5, 2],
         [8, 3, 2]]]])

In [77]:
temp8 = a3a[:,:,np.newaxis]
temp8

array([[[[1, 2, 3]],

        [[3, 2, 1]],

        [[4, 5, 6]]],


       [[[7, 8, 9]],

        [[9, 8, 7]],

        [[6, 5, 4]]],


       [[[9, 5, 1]],

        [[1, 5, 2]],

        [[8, 3, 2]]]])

In [78]:
temp6.shape

(1, 3, 3, 3)

In [79]:
temp7.shape

(3, 1, 3, 3)

In [80]:
temp8.shape

(3, 3, 1, 3)

## *How to reduce dimension of an array?*
Easy and famous methods to reduce the dimension of an array are:
- np.array.reshape method
- np.array.flatten method
- np.array.ravel method
- flatten and ravel methods are used to convert the array into 1D array or vector

### converting 4D array to 3D array

In [92]:
#Using reshape method
t1 = temp6.reshape(3,3,3)
t1

array([[[1, 2, 3],
        [3, 2, 1],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7],
        [6, 5, 4]],

       [[9, 5, 1],
        [1, 5, 2],
        [8, 3, 2]]])

### Converting 3D to 2D

In [110]:
t4 = a3a.reshape(a3a.shape[0],a3a.shape[1]*a3a.shape[2]) # This is equal to (3,9) because 3*9 = 3*3*3
t4

array([[1, 2, 3, 3, 2, 1, 4, 5, 6],
       [7, 8, 9, 9, 8, 7, 6, 5, 4],
       [9, 5, 1, 1, 5, 2, 8, 3, 2]])

### Converting 2D or higher array to 1D array
- flatten and ravel is best method to do so

In [111]:
t2 = temp8.flatten()
t2

array([1, 2, 3, 3, 2, 1, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 9, 5, 1, 1,
       5, 2, 8, 3, 2])

In [115]:
t3 = a3f.ravel()
t3

array([32, 19, 64, 40, 23,  6, 31, 82, 58, 79, 57, 91, 42, 20, 50, 27,  8,
       49,  0, 43, 41, 89, 12, 82, 70, 91, 35, 89, 50, 43, 75, 45, 51, 59,
       75, 90, 46, 71, 69, 69, 21, 39, 60, 37, 12, 67, 58, 50, 52, 23, 77,
       86, 48, 88, 46, 97,  7, 51, 43,  5, 52, 72, 60, 17, 86, 82, 25, 58,
       92, 30, 61, 16])

## *How to find unique elements from array?*

In [127]:
uni1 = np.unique(t3)
uni1

array([ 0,  5,  6,  7,  8, 12, 16, 17, 19, 20, 21, 23, 25, 27, 30, 31, 32,
       35, 37, 39, 40, 41, 42, 43, 45, 46, 48, 49, 50, 51, 52, 57, 58, 59,
       60, 61, 64, 67, 69, 70, 71, 72, 75, 77, 79, 82, 86, 88, 89, 90, 91,
       92, 97])

In [128]:
uni2 = np.unique(t2)
uni2 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
uni3 = np.unique(a2i)
uni3

array([1, 2, 3, 4, 5])

## *Basic Operations on array*
- Note that: For array operations the dimension and the no. of elements of each array should be same 

### Addition

In [134]:
#1D array addition
a1a+a1b 

array([ 2,  5,  8, 11, 14])

In [137]:
a1c + a1d

array([1., 1., 1., 1., 1.])

In [151]:
#2D array addition
a2a+a2h.astype(np.uint8) #Changing type of a2h because it was in floating point numbers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
#3D array addition
a3i = np.random.randint(low=1,high=100,size=(3,3,3))

In [166]:
a3a+a3i

array([[[ 87,  76,  33],
        [ 86,  68,  43],
        [ 58,  33,   7]],

       [[  8,  39,  14],
        [ 38,  15,  17],
        [ 19,   8,  17]],

       [[ 11,  24,  76],
        [ 86,  20,  12],
        [103,  28,  35]]])

### Subtraction

In [167]:
#1D array Subtraction
a1a-a1b 

array([ 0, -1, -2, -3, -4])

In [168]:
a1c - a1d

array([-1., -1., -1., -1., -1.])

In [183]:
#2D array Subtraction
a2h=a2h.astype(np.uint8) #Changing type of a2h because it was in floating point numbers
a2a-a2h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
#3D array Subtraction
a3i = np.random.randint(low=1,high=100,size=(3,3,3))

a3a-a3i

array([[[-73, -27, -61],
        [-70, -44, -49],
        [-73, -11, -85]],

       [[-92, -58, -72],
        [-38, -82, -27],
        [-28, -91, -51]],

       [[-62,   3, -60],
        [-71, -34, -52],
        [-66, -49, -82]]])

### Multiplication

In [171]:
#1D array 
a1a*a1b

array([ 1,  6, 15, 28, 45])

In [184]:
#2D array 
a2a*a2h

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [173]:
#3D array
a3i = np.random.randint(low=1,high=100,size=(3,3,3))

a3a*a3i

array([[[ 25,  86, 153],
        [108, 190,  44],
        [120, 335,  54]],

       [[693, 720, 864],
        [594, 304,   7],
        [ 18, 425, 100]],

       [[567, 320,   6],
        [ 76, 465,  28],
        [200, 252,  46]]])

### Concatenation 

In [180]:
# 1D array
a= np.concatenate((a1a,a1b))
a

array([1, 2, 3, 4, 5, 1, 3, 5, 7, 9])

In [187]:
# 2D array
b = np.concatenate((a2h,a2a),axis=0)
b

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
b = np.concatenate((a2h,a2a),axis=1)
b

array([[ 0,  0,  0,  0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  5,  6,  7,  8],
       [ 0,  0,  0,  0,  9, 10, 11, 12]])

In [189]:
# 3D array
c=np.concatenate((a3a,a3i),axis=0)
c

array([[[ 1,  2,  3],
        [ 3,  2,  1],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 9,  8,  7],
        [ 6,  5,  4]],

       [[ 9,  5,  1],
        [ 1,  5,  2],
        [ 8,  3,  2]],

       [[25, 43, 51],
        [36, 95, 44],
        [30, 67,  9]],

       [[99, 90, 96],
        [66, 38,  1],
        [ 3, 85, 25]],

       [[63, 64,  6],
        [76, 93, 14],
        [25, 84, 23]]])

In [190]:
c=np.concatenate((a3a,a3i),axis=1)
c

array([[[ 1,  2,  3],
        [ 3,  2,  1],
        [ 4,  5,  6],
        [25, 43, 51],
        [36, 95, 44],
        [30, 67,  9]],

       [[ 7,  8,  9],
        [ 9,  8,  7],
        [ 6,  5,  4],
        [99, 90, 96],
        [66, 38,  1],
        [ 3, 85, 25]],

       [[ 9,  5,  1],
        [ 1,  5,  2],
        [ 8,  3,  2],
        [63, 64,  6],
        [76, 93, 14],
        [25, 84, 23]]])

## *Broadcasting*
Note That: For broadcasting there is no need to have same dimensions. 

In [193]:
a1a * 3

array([ 3,  6,  9, 12, 15])

In [196]:
a2e * 0.5

array([[ 0.5,  6. ],
       [11.5, 17. ],
       [22.5, 28. ],
       [33.5, 39. ],
       [44.5, 50. ]])

In [198]:
a3a + 22

array([[[23, 24, 25],
        [25, 24, 23],
        [26, 27, 28]],

       [[29, 30, 31],
        [31, 30, 29],
        [28, 27, 26]],

       [[31, 27, 23],
        [23, 27, 24],
        [30, 25, 24]]])

## *Numpy useful functions*

In [199]:
a1a.min()

1

In [201]:
a1a.max()

5

In [202]:
a1a.sum() # Sum of all the elements present in the array

15

In [205]:
a2f.min()

3

In [208]:
a2g.max()

1.0

In [209]:
a2g.sum()

4.0

In [210]:
a3a.min()

1

In [211]:
a3a.max()

9

In [212]:
a3a.sum()

126

### How to find min, max in axis wise?

In [218]:
a3a.min(axis=1) #axis = 0 means the 1st axis i.e., columns

array([[1, 2, 1],
       [6, 5, 4],
       [1, 3, 1]])

In [221]:
a3a.min(axis=0)

array([[1, 2, 1],
       [1, 2, 1],
       [4, 3, 2]])

In [219]:
a3a.max(axis=1) #col wise

array([[4, 5, 6],
       [9, 8, 9],
       [9, 5, 2]])

In [220]:
a3a.max(axis=0) #row wise

array([[9, 8, 9],
       [9, 8, 7],
       [8, 5, 6]])

### Sorting

In [222]:
np.sort(a1a)

array([1, 2, 3, 4, 5])

In [223]:
np.sort(a2a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [233]:
np.sort(a2g)

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])